### ISSUE TITLE
Buttons custom emotes not working

### ISSUE THREAD

**Issue by DestopLine** [mccoderpy/discord.py-message-components#2]
Custom emotes don't work, but reviewing the `components.py` code, I saw that `base.__setitem__('emoji', self._emoji.to_dict())` makes a dictionary to send it in the JSON data, but discord.py storages the emoji ID as an int, while the Discord API requires it to be a string despite it being all digits. When the payload is sent, the API receives an int as emote ID instead of a string, causing the custom emote not to show.

**Comment by mccoderpy** [comment]
Hi, sorry for replying so late, I just woke up😃. As you can see [here](https://discord.com/developers/docs/interactions/message-components#component-object) Discord needs a Partieles-Emoji-Object in the case. as you noticed there are some (not only small) bugs; these will be fixed in an update which will probably come out today until tomorrow.

**Comment by mccoderpy** [comment]
You can already find the version in the [developer-branch](https://github.com/mccoderpy/discord.py-message-components/tree/developer) (there have been some changes so it is no longer called `discord.RawInteractionCreateEvent` but `discord.Interaction`). also you can now use `on_button_click` instead of `on_interaction_create` (note that this passes 2 objects: one representing the interaction object and one representing the button you got before with `interaction.button.custom_id`; you now get this in the second object with `parametername.custom_id`).

**Comment by mccoderpy** [comment]
[Update](https://pypi.org/project/discord.py-message-components/1.7.5/) is out @DestopLine

**Comment by mccoderpy** [comment]
And [Documentation](https://discordpy-message-components.readthedocs.io/en/latest/) too

**Comment by DestopLine** [comment]
Nice! Great library btw

**Comment by mccoderpy** [comment]
Thank you very much 😂
